-- Estate Agents

CREATE TABLE ESTATE_AGENT (
  ID       INTEGER     NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 1, INCREMENT BY 1, NO CACHE ) PRIMARY KEY,
  NAME     VARCHAR(255),
  ADDRESS  VARCHAR(255),
  LOGIN    VARCHAR(40) NOT NULL UNIQUE,
  PASSWORD VARCHAR(40)
);

-- Person

CREATE TABLE PERSON (
  ID         INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 1, INCREMENT BY 1, NO CACHE ) PRIMARY KEY,
  FIRST_NAME VARCHAR(255),
  NAME       VARCHAR(255),
  ADDRESS    VARCHAR(255)
);

-- Contracts with inheritance

CREATE TABLE CONTRACT (
  ID          INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 1, INCREMENT BY 1, NO CACHE ) PRIMARY KEY,
  CONTRACT_NO VARCHAR(255),
  DATE        DATE,
  PLACE       VARCHAR(255)
);

CREATE TABLE TENANCY_CONTRACT (
  CONTRACT_ID      INTEGER NOT NULL PRIMARY KEY,
  START_DATE       DATE,
  DURATION         INTEGER,
  ADDITIONAL_COSTS DECIMAL(8, 2),
  CONSTRAINT FK_CONTRACT FOREIGN KEY (CONTRACT_ID) REFERENCES CONTRACT (ID)
);

CREATE TABLE PURCHASE_CONTRACT (
  CONTRACT_ID        INTEGER NOT NULL PRIMARY KEY,
  NO_OF_INSTALLMENTS INTEGER,
  INTEREST_RATE       DECIMAL(8, 5),
  CONSTRAINT FK_CONTRACT FOREIGN KEY (CONTRACT_ID) REFERENCES CONTRACT (ID)
);

-- Estates

CREATE TABLE ESTATE (
  ID            INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 1, INCREMENT BY 1, NO CACHE ) PRIMARY KEY,
  MANAGER_ID    INTEGER NOT NULL,
  PERSON_ID     INTEGER DEFAULT NULL,
  CONTRACT_ID   INTEGER DEFAULT NULL,
  CITY          VARCHAR(255),
  POSTAL_CODE   VARCHAR(50),
  STREET        VARCHAR(255),
  STREET_NUMBER VARCHAR(50),
  SQUARE_AREA   INTEGER,
  CONSTRAINT FK_MANAGER FOREIGN KEY (MANAGER_ID) REFERENCES ESTATE_AGENT (ID),
  CONSTRAINT FK_PERSON FOREIGN KEY (PERSON_ID) REFERENCES PERSON (ID),
  CONSTRAINT FK_CONTRACT FOREIGN KEY (CONTRACT_ID) REFERENCES CONTRACT (ID)
);

CREATE TABLE APARTMENT (
  ESTATE_ID        INTEGER NOT NULL PRIMARY KEY,
  FLOOR            VARCHAR(50),
  RENT             DECIMAL(8, 2),
  ROOMS            INTEGER,
  BALCONY          SMALLINT,
  BUILT_IN_KITCHEN SMALLINT,
  CONSTRAINT FK_ESTATE FOREIGN KEY (ESTATE_ID) REFERENCES ESTATE (ID)
);

CREATE TABLE HOUSE (
  ESTATE_ID INTEGER NOT NULL PRIMARY KEY,
  FLOORS    VARCHAR(50),
  PRICE     DECIMAL(8, 2),
  GARDEN    SMALLINT,
  CONSTRAINT FK_ESTATE FOREIGN KEY (ESTATE_ID) REFERENCES ESTATE (ID)
);
