INSERT INTO VSISP15.ESTATE_AGENT (NAME, ADDRESS, LOGIN, PASSWORD) VALUES ('Joana Sieranski', 'Hamburg', 'joanna', 'demo');
INSERT INTO VSISP15.ESTATE_AGENT (NAME, ADDRESS, LOGIN, PASSWORD) VALUES ('Tobias Fechner', 'Hamburg', 'tobi', 'demo');
INSERT INTO VSISP15.ESTATE_AGENT (NAME, ADDRESS, LOGIN, PASSWORD) VALUES ('Konstantin Möllers', 'Hamburg', 'corny', 'demo');

INSERT INTO VSISP15.PERSON (FIRST_NAME, NAME, ADDRESS) VALUES ('Joanna', 'Sieranski', 'Hamburg');
INSERT INTO VSISP15.PERSON (FIRST_NAME, NAME, ADDRESS) VALUES ('Tobias', 'Fechner', 'Rahlstedt');
INSERT INTO VSISP15.PERSON (FIRST_NAME, NAME, ADDRESS) VALUES ('Konstantin', 'Möllers', 'Stellingen');

INSERT INTO VSISP15.ESTATE (MANAGER_ID, CITY, POSTAL_CODE, STREET, STREET_NUMBER, SQUARE_AREA) VALUES (1, 'Hamburg', '22527', 'Stellinger Steindamm', '34A', 31);
INSERT INTO VSISP15.APARTMENT (ESTATE_ID, FLOOR, RENT, ROOMS, BALCONY, BUILT_IN_KITCHEN) VALUES (1, 'EG', 400.00, 3, 1, 1);

INSERT INTO VSISP15.CONTRACT (CONTRACT_NO, DATE, PLACE, PERSON, ESTATE) VALUES ('2013-02-01-AAAA', '2013-02-01', 'Hamburg', 1, 1);
INSERT INTO VSISP15.TENANCY_CONTRACT (CONTRACT_ID, START_DATE, DURATION, ADDITIONAL_COSTS) VALUES (1, '2013-05-14', 100, 42.00);
